// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sgokul961/echo-hub-notification-svc/pkg/api"
	"github.com/sgokul961/echo-hub-notification-svc/pkg/api/handler"
	"github.com/sgokul961/echo-hub-notification-svc/pkg/config"
	"github.com/sgokul961/echo-hub-notification-svc/pkg/db"
	"github.com/sgokul961/echo-hub-notification-svc/pkg/repository"
	"github.com/sgokul961/echo-hub-notification-svc/pkg/usecase"
)

// Injectors from wire.go:

func InitApi(cfg config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.Init(cfg)
	if err != nil {
		return nil, err
	}
	notifyRepoInterface := repository.NewNotificationRepo(gormDB)
	notifyUsecaseInterface := usecase.NewUserUserUseCase(notifyRepoInterface)
	notificationHandler := handler.NewNotificationHandler(notifyUsecaseInterface)
	serverHTTP := api.NewServerHttp(notificationHandler)
	return serverHTTP, nil
}
